### ISSUE TITLE
Styling a rounded dialog does not work due to the pre-set background #fff

### ISSUE THREAD

**Issue by benjaminapetersen** [Polymer/paper-dialog#45]
The paper dialog has css:

``` css
:host {
      background: #fff;
     /* other css... */
}
```

Which, if you set:

``` css
html /deep/ .rounded_dialog::shadow #scroller {
  border-radius: 10px;
}
```

Will cause white corners to show behind the dialog.  Setting the background color to none, by adding this rule:

``` css
html /deep/ .rounded_dialog::shadow #scroller {
  border-radius: 10px;
  background: none;
}
```

Will cause the #scroller and #actions to be transparent as well.  Setting a background color to #scroller & #actions will create some quirky corner effects between the #scroller & #actions.
